### ISSUE TITLE
run: consider seccomp-bpf switches or deprecating run

### ISSUE THREAD

**Issue by nwmcsween** [arsv/sninit#2]
Linux has a multitude of various programs that run duplicates and to be useful imo would have to push in more. There are two possible ways to go about fixing this:
1. Create seccomp-bpf switches within run which would become massive due to individual arg checking.
2. Create utilities to chain things together without having to use sh, hopefully as an example:
   `/bin/cgexec args /run-as-cmd /bin/unshare args /seccomp-bpf-cmd args`

**Comment by arsv** [comment]
Linux is a kernel, and those tools are only there if whoever builds the system decides so.
It's not that difficult to build a system without standalone cgexec or unshare or setcap for instance, at which point having an option to use run instead may be beneficial.

Adding seccomp is a neat idea, but maybe not as a part of run. The idea behind run is to merge several smaller common tools to avoid excessive chaining. At some point, it's no longer excessive — I would probably prefer seccomp as a separate tool because of all the parsing involved.
