### ISSUE TITLE
Initdir: Allow inittab style?

### ISSUE THREAD

**Issue by nwmcsween** [arsv/sninit#3]
For a real world example imagine trying to allow various syslogs with the initdir where everything is a service you cannot make syslog stop at end (L) and editing and commenting inittab everytime a user changes something is brittle.

**Comment by arsv** [comment]
Initdir is not ordered in any way, there is no "end" there. That's why ordered entries go into inittab, it's not just a matter of convenience.

There was a way to put flags into initdir files at some point, but it got removed. Mostly because any reasonably attempt to use them would rely on some fragile assumptions.

**Comment by nwmcsween** [comment]
Not starting flags, stopping flags as in this should try to get stopped
first or last. Use cases for all in order: a monitoring daemon such as
nagios so it doesn't send out a dozen emails on shutdown, syslog. Thinking
out loud and the complexity might out way the benefits but maybe states
would be a useful addition such as start starting, running, stopping.

**Comment by arsv** [comment]
It's not only the complexity. There is no nice reliable way to distinguish between "starting" and "running" state, there's only some interval of time from fork return until waitpid reporting child death, with almost complete uncertainty in-between.

Nagios itself does something that's inherently unreliable, namely monitoring processes that aren't its children. So it has to come up with some sort of assumptions, and it may be better to tweak those assumptions instead.

Stop-first does make sense, there are at least two easy ways to implement it. The question is, whatever needs to be stopped first, how is it expected to handle start-up? It can't be started last.

How to implement, well, one option is to have "non-monitored" and "monitored" runlevels, let's say 3 and 4, mark regular services 34 and monitoring services 4, and do a sort of staged startup and staged shutdown, 0->3->4-4-4-4->3->0. Monitors will be stopped before everything else during 4->3 transition this way. Doing this requires some scripting, and probably a bunch of nasty assumptions around 3->4 transition, which is why I think it's better to do it in scripts and not in init.

Another way is to read a second inittab after initdir parsing, or allow initdir to be included at arbitrary point within inittab, and put start-last-stop-first entries after inittab. The thing is, it would work exactly like the staged setup above, with a bit less scripting and a bit more logic hard-coded into init.
