### ISSUE TITLE
init can be run without PID = 1

### ISSUE THREAD

**Issue by metalgrid** [arsv/sninit#5]
Is there a reason to be able to run `init` not as PID 1?
I've built my system with sninit and it's great but I also use `telegraf` for monitoring. Thing is, `telegraf` runs `/sbin/init --version` which doesn't do anything special in `sninit` - instead it attempts to reinitialize the system, along with mounting, spawning getty's, services and so on.
Can we either implement `--version` or at least check if we're PID 1 and if not - refuse to start (or both) ?

**Comment by arsv** [comment]
sninit can be run from the source during development. That's the original reason for this line:

https://github.com/arsv/sninit/blob/master/init.c#L440

If you want it to abort when not running as pid 1, move the line to the top of the function (before setup() call probably) and make it return -1 instead of 0.

That said, fixing init to meet random expectations of a logging system (?) sounds like a horrible idea. The logger should not be spawning `/sbin/init` in the first place. If anything, it should be calling the client tool, `telinit`, instead. Even then, blindly assuming it has to be a GNU tool that takes `--version` is strage. Telegraf is supposed to be modular, so I guess it might be better to fix the module there that tries to spawn init, and stop it from doing that.

**Comment by Metalgrid** [comment]
Thanks for the explanation, that makes perfect sense.

As for `telegraf`, its behaviour is weird on its own and I'll be opening an issue for that. But given the circumstances, I can't imagine what else would try to be smart about init systems and invoke init for whatever reason. As for telegraf, it always spawns init, even if called with `--version` or `--help`, without having a configuration file at all.
I don't know the reasoning behind this, but it just makes a terrible mess, and if something popular like telegraf does this, chances are there's going to be other senseless software out there that would try too. That's why I'd like to prevent init from running when pid != 1. Thanks again for your help!
